## Task-1 # Question - 1

In [1]:
# Write a function to compute 5/0 and use try/catch to catch the exceptions

def division():
    try:
        user_input = float(input("enter a number: ")) #To input the numerical value
        output = user_input/0
        print("The result is : ",output)
    except (ValueError,ZeroDivisionError) as e:
        print(e) #To print the error message
        
#Calling the function
division()

enter a number: 5
float division by zero


## Task-1 # Question - 2

In [2]:
#Generate sentences based on given data

def gen_sentences(sub,verb,obj):
    for i in range(len(sub)):
        for j in range(len(verb)):
            for k in range(len(obj)):
                output = sub[i]+" "+verb[j]+" "+obj[k]
                print(output)
    
list_of_subjects = ["Americans","Indians"]
list_of_verbs = ["play","watch"]
list_of_objects = ["Baseball","Cricket"]

#Function which generates the sentences
gen_sentences(list_of_subjects,list_of_verbs,list_of_objects)

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


## Task-2 # Question - 1

In [4]:
# To generate alexandre-theophile vandermonde matrix with geometric progression

import numpy as np
num_lst = [1,2,3,4]                # 'num_lst' : The input vector list
x = np.array(num_lst)              # 'x'       : The converted list to array
N = 4                              # 'N'       : The no.of columns in the output matrix

#If increasing is False, the output colums will be x**(N-1), x**(N-2).... x**0
vander_mtrx_false = np.vander(x,N,increasing=False)
print("If increasing is false, the vandermonde matrix is : \n", vander_mtrx_false)

print('-'*50)

#If increasing is True, the output colums will be x**0, x**1....x**(N-1)  .Reverse of false matrix.
vander_mtrx_true = np.vander(x,N,increasing=True)
print("If increasing is true, the vandermonde matrix is : \n", vander_mtrx_true)


If increasing is false, the vandermonde matrix is : 
 [[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]
--------------------------------------------------
If increasing is true, the vandermonde matrix is : 
 [[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]
 [ 1  4 16 64]]
